%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ADMIN\OneDrive\Documents\MATLAB\spring25\denisondata\coursePrereqs.csv
%
% Auto-generated by MATLAB on 09-Dec-2024 02:31:35

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 4);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Course", "Prereq1", "Prereq2","Prereq3"];
opts.VariableTypes = ["string", "string", "string","string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Course", "Prereq1", "Prereq2","Prereq3"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Course", "Prereq1", "Prereq2","Prereq3"], "EmptyFieldRule", "auto");

% Import the data
course_prereqs = readmatrix("denison_data\denison_prereqs.csv", opts);
course_prereqs = cellstr(course_prereqs);

%% Clear temporary variables
clear opts