%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ADMIN\OneDrive\Documents\MATLAB\spring25\denisondata\buckets.csv
%
% Auto-generated by MATLAB on 09-Dec-2024 02:37:53

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Bucket", "VarName2"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Bucket", "VarName2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Bucket", "VarName2"], "EmptyFieldRule", "auto");

% Import the data
buckets = readmatrix("denison_data\denison_buckets.csv", opts);
buckets = cellstr(buckets);

%% Clear temporary variables
clear opts