%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ADMIN\OneDrive\Documents\MATLAB\spring25\redofakedata\courseSchedules.csv
%
% Auto-generated by MATLAB on 19-Nov-2024 01:12:33

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Course", "F2024", "S2024", "F2023", "S2023", "F2022", "S2022", "F2021","S2021"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double", "double","double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Course", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Course", "EmptyFieldRule", "auto");

% Import the data
courseSchedules = readtable("wooster_data\wooster_schedule.csv", opts);


%% Clear temporary variables
clear opts