%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: college_structure.csv
%
% Auto-generated by MATLAB on 09-Nov-2024 12:52:34

%% Setup the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 2);

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Fall", "Spring"];
opts.VariableTypes = ["double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Import the data
college_structure = readtable("wooster_data\wooster_structure.csv", opts);

%% Convert to output type
college_structure = table2array(college_structure);

%% Clear temporary variables
clear opts