%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Users\ADMIN\OneDrive\Documents\MATLAB\spring25\redofakedata\courseSchedules.csv
%
% Auto-generated by MATLAB on 19-Nov-2024 01:12:33

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 9, "Encoding", "UTF-8");

% Specify range and delimiter
opts.DataLines = [2, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Course", "Spring 23","Winter 23","Fall 22","Spring 22","Winter 22","Fall 21"];
opts.VariableTypes = ["string", "double", "double", "double", "double", "double", "double"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, "Course", "WhitespaceRule", "preserve");
opts = setvaropts(opts, "Course", "EmptyFieldRule", "auto");

% Import the data
courseSchedules = readtable("carleton_data\carleton_schedule.csv", opts);


%% Clear temporary variables
clear opts