%% Import data from text file
% Script for importing data from the following text file:
%
%    filename: C:\Huy Phan\College\math-major-spring25\kenyon\kenyondata\kenyon_buckets.csv
%
% Auto-generated by MATLAB on 04-Mar-2025 14:04:08

%% Set up the Import Options and import the data
opts = delimitedTextImportOptions("NumVariables", 7);

% Specify range and delimiter
opts.DataLines = [1, Inf];
opts.Delimiter = ",";

% Specify column names and types
opts.VariableNames = ["Bucket", "VarName2"];
opts.VariableTypes = ["string", "string"];

% Specify file level properties
opts.ExtraColumnsRule = "ignore";
opts.EmptyLineRule = "read";

% Specify variable properties
opts = setvaropts(opts, ["Bucket", "VarName2"], "WhitespaceRule", "preserve");
opts = setvaropts(opts, ["Bucket", "VarName2"], "EmptyFieldRule", "auto");

% Import the data
buckets = readmatrix("wellesley_data\wellesley_buckets.csv", opts);
buckets = cellstr(buckets);


%% Clear temporary variables
clear opts